const SET_ERROR = 'SET_ERROR';
const SET_TOKEN = 'SET_TOKEN';
const SET_PLAYLIST = 'SET_PLAYLIST';
const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
const FETCH_PLAYLIST_ASYNC = 'FETCH_PLAYLIST_ASYNC';
const ENABLE_REFRESH_BUTTON = 'ENABLE_REFRESH_BUTTON';
const DISABLE_REFRESH_BUTTON = 'DISABLE_REFRESH_BUTTON';
const FETCH_PLAYLIST_ASYNC_END = 'FETCH_PLAYLIST_ASYNC_END';

export {
  SET_TOKEN,
  SET_ERROR,
  SET_PLAYLIST,
  SET_CURRENT_SONG,
  FETCH_PLAYLIST_ASYNC,
  ENABLE_REFRESH_BUTTON,
  DISABLE_REFRESH_BUTTON,
  FETCH_PLAYLIST_ASYNC_END
};
