const IS_PLAYLIST_FETCHING = 'IS_PLAYLIST_FETCHING';
const PLAYLIST_FETCH_DONE = 'PLAYLIST_FETCH_DONE';
const SET_PLAYLIST_PLACEHOLDER = 'SET_PLAYLIST_PLACEHOLDER';
const SET_PLAYLIST = 'SET_PLAYLIST';
const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
const ADD_SONG_SUGGESTION = 'ADD_SONG_SUGGESTION';
const FETCH_PLAYLIST_ASYNC = 'FETCH_PLAYLIST_ASYNC';

export {
  FETCH_PLAYLIST_ASYNC,
  IS_PLAYLIST_FETCHING,
  PLAYLIST_FETCH_DONE,
  SET_PLAYLIST_PLACEHOLDER,
  SET_PLAYLIST,
  SET_CURRENT_SONG,
  ADD_SONG_SUGGESTION
};
